### ISSUE TITLE
Zig upstream tracking issues

### ISSUE THREAD

**Issue by kassane** [kassane/zig-esp-idf-sample#13]
- [x] https://github.com/ziglang/zig/issues/20663
- [ ] https://github.com/ziglang/zig/issues/20630
- [ ] https://github.com/ziglang/zig/issues/20327
- [ ] https://github.com/ziglang/zig/issues/20875
- [ ] https://github.com/ziglang/zig/issues/5467
- [ ] [Allow overriding `std.Io.File`, `std.Io.Dir`](https://codeberg.org/ziglang/zig/issues/30604)
- [x] https://github.com/ziglang/zig/issues/25650
  - [ ] https://github.com/espressif/llvm-project/issues/4
